version: '3.1'

services:
  angular:
    build: angular
    restart: always
    container_name: angular_container
    ports:
      - "8420:8420"
    depends_on:
      - gateway
      - mongo
  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always
  zookeeper:
    image: zookeeper:3.5.9
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka:3.2
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  eureka:
    build: eureka-registry
    restart: on-failure
    ports:
      - "8761:8761"
  gateway:
    build: gateway
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - eureka
  car-micro-api:
    build: car-micro-api
    restart: always
    container_name: car_api
    depends_on:
      - eureka
      - gateway
  car-micro-server:
    build: car-micro-server
    restart: on-failure
    container_name: car_server
    depends_on:
      - car-micro-api

  user-micro-api:
    build: user-micro-api
    restart: always
    container_name: user_api
    depends_on:
      - eureka
      - gateway
  user-micro-server:
    build: user-micro-server
    restart: on-failure
    container_name: user_server
    depends_on:
      - user-micro-api

