version: '3.8'

services:
  angular:
    build: angular
    restart: always
    container_name: angular_container
    ports:
      - "8420:8420"
    depends_on:
       gateway:
         condition: service_healthy
       mongo:
         condition: service_healthy
  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: on-failure
    healthcheck:
      test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
  zookeeper:
    image: zookeeper:3.5.9
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka:3.2
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
       zookeeper:
         condition: service_started
  eureka:
    build: eureka-registry
    container_name: eureka
    restart: on-failure
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 20
  gateway:
    build: gateway
    container_name: gateway
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
       eureka:
         condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 20
  car-micro-api:
    build: car-micro-api
    restart: always
    container_name: car_api
    depends_on:
       eureka:
         condition: service_started
       gateway:
         condition: service_started
  car-micro-server:
    build: car-micro-server
    restart: on-failure
    container_name: car_server
    depends_on:
       car-micro-api:
         condition: service_started

  user-micro-api:
    build: user-micro-api
    restart: always
    container_name: user_api
    depends_on:
       eureka:
         condition: service_started
       gateway:
         condition: service_started
  user-micro-server:
    build: user-micro-server
    restart: on-failure
    container_name: user_server
    depends_on:
       user-micro-api:
         condition: service_started

