spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-api
          uri: lb://user-micro-api
          predicates:
            - Path=/user/**
        - id: car-api
          uri: lb://car-micro-api
          predicates:
            - Path=/vehicle/**
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
management:
  endpoint:
    gateway:
      enabled: true
