spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: user-api
          uri: lb://USER-API
          predicates:
            - Path=/user/**
        - id: car-api
          uri: lb://CAR-API
          predicates:
            - Path=/car/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

server:
  port: 8080