spring:
  application:
    name: car-micro-server
server:
  port: ${PORT:0}
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}