spring:
  application:
    name: user-micro-server
server:
  port: ${PORT:0}
spring.data.mongodb:
  uri: mongodb://mongo:27017
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}