spring:
  application:
    name: user-micro-api
  cloud:
    discovery:
      enabled: true
    stream:
      bindings:
        output:
          destination: queue.text
      kafka:
        binder:
          brokers: kafka
          defaultBrokerPort: 9092
server:
  port: ${PORT:0}
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    hostname: localhost
    preferIpAddress: true